import "./globals.css";
import { Providers } from "./GlobalRedux/provider";
import { store } from "./GlobalRedux/store";
import { fetchUsers } from "./GlobalRedux/Features/users/userSlice";

store.dispatch(fetchUsers());

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
